[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
pumpg = "4ZYeZiZEeAd2oyHKVsMX48z7AjVsyrVE7x2D5s8DMuqt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
# cluster = "https://few-twilight-wish.solana-devnet.quiknode.pro/5337a237aaeecd58b8c43a375c78a541aafccf04"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.mainnet-beta.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

# cp-swap program in mainnet
[[test.validator.clone]]
address = "CPMMoo8L3F4NbTegBCKVNunggL7H1ZpdTHKxQB5qKP1C"

# cp-swap create_pool_fee_reveiver in mainnet
[[test.validator.clone]]
address = "DNXgeM9EiiaAbaWvwjHj9fQQLAX5ZsfHyvmYUNRAdNC8"

# cp-swap ammConfig in mainnet
[[test.validator.clone]]
address = "D4FPEruKEHrG5TenZ2mpDGEfu1iUvTiqBxvpU8HLBvC2"

# raydium-locking program in mainnet
[[test.validator.clone]]
address = "LockrWmn6K5twhz3y9w1dQERbmgSaRkfnTeTKbpofwE"

# raydium-locking authority in mainnet
[[test.validator.clone]]
address = "3f7GcQFG397GAaEnv51zR6tsTVihYRydnydDD1cXekxH"

# metadata program in mainnet
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"

